# Site settings
title: The Lacking Organization
tagline: with your host Julius C. Lacking
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lacking.org" # the base hostname & protocol for your site
host: 0.0.0.0

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"


# Plugins
plugins: ["jekyll-paginate-v2"]

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
