# Site settings
title: The Lacking Organization
tagline: with your host Julius C. Lacking
description: >
  The natural confluence of all things Lacking, including playlists,
  podcasts, pernicious ponderings, and other perusable presumptions
  born of the arduous task that is the Lacking Organization.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lacking.org" # the base hostname & protocol for your site
host: 0.0.0.0

defaults:
  -
    scope:
      path: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
    values:
      layout: "post"

collections:
  contributors:
    output: true

# Plugins
plugins: ["jekyll-paginate-v2"]
amplitude_version: 3.2.3
# Build settings
excerpt_separator: <!--more-->
markdown: kramdown
sass:
  sass_dir: assets/sass

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
