# Site settings
title:          The Lacking Organization
tagline:        with your host Julius C. Lacking
description: >
                The natural confluence of all things Lacking, including playlists,
                podcasts, pernicious ponderings, and other perusable presumptions
                born of the arduous task that is the Lacking Organization.
baseurl:        ""
url:            https://the.lacking.org
published_url:  https://the.lacking.org

# Social Media
social:
  twitter: jclacking
  facebook: jclacking

# Site Map
sitemap:
  filename: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"
    - "/podcast/podcast.rss"
    - "/assets/css/main.css"
  include_posts:
    - "index.html"
    - "/playlists/index.html"
    - "/podcast/index.html"
  # change_frequency_name: "frequency"
  priority_name: "priority"

# Podcast Feed Settings
podcast:
  title:        The Lacking Organization
  subtitle:     with your host Julius C. Lacking
  email:        julius@lacking.org
  description: >
                The sonic essence of all that is Lacking, this podcast explores a
                variety of music with a decidedly random approach.
  keywords:     music,eclectic
  baseurl:      /podcast
  lang:         en
  author:       Julius C. Lacking
  copyright:    "&#x2117; &amp; &#xA9; 2018"
  file_url:     http://audio.lacking.org


# Dev
# host: 0.0.0.0

defaults:
  -
    scope:
      path: "pages"
    values:
      layout: "page"
      priority: 0.8
  -
    scope:
      path: "playlists"
    values:
      layout: "playlist"
      permalink: /playlists/:year/:year-:month-:day-:title
      priority: 0.5
  -
    scope:
      path: "podcast"
    values:
      layout: "playlist"
      # layout: "podcast"
      permalink: /podcast/:year/:title
      priority: 0.7
  -
    scope:
      path: ""
    values:
      layout: "post"
      priority: 0.6

collections:
  contributors:
    output: true

# Plugins
plugins:
  - jekyll-paginate-v2
  - jekyll-analytics
  - jekyll-sitemap
  - jekyll-last-modified-at
  # - searchyll

# Plugin Configuration
amplitude_version: 3.2.3
jekyll_analytics:
  GoogleAnalytics:
    id: UA-120546300-1
elasticsearch:
  # url: https://hw87e7ielk:s7mrjptjn9@tlo-testing-5782922639.us-west-2.bonsaisearch.net
  index_name: the-lacking-org-dev
monthly_archive:
  layout: index
  path: archives

# Build settings
excerpt_separator: <!--more-->
markdown: kramdown
sass:
  sass_dir: assets/sass

# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
